# https://jekyllrb.com/docs/configuration/options/

# Server
source: src
destination: _site
keep_files:
  - assets/css
  - assets/js
host: "0.0.0.0"
baseurl: ""
exclude:
  - assets/scss
  - assets/js
  - assets/options

